{{- if eq .Values.mode "watch" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clusterstate-agent.fullname" . }}
  labels:
    {{- include "clusterstate-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "clusterstate-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        suppline.io/release-revision: {{ .Release.Revision | quote }}
      labels:
        {{- include "clusterstate-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clusterstate-agent.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: clusterstate-agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        env:
        - name: SUPPLINE_URL
          value: {{ required "suppline.url is required" .Values.suppline.url | quote }}
        - name: CLUSTER_NAME
          value: {{ required "clusterName is required" .Values.clusterName | quote }}
        - name: EXCLUDED_NAMESPACES
          value: {{ .Values.excludedNamespaces | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.logLevel | quote }}
        - name: AGENT_MODE
          value: "watch"
        - name: WATCH_FLUSH_INTERVAL
          value: {{ .Values.watchFlushInterval | quote }}
        {{- if .Values.suppline.apiKey }}
        - name: SUPPLINE_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "clusterstate-agent.fullname" . }}-apikey
              key: api-key
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
{{- end }}