{{- if .Values.suppline.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterstate-agent.fullname" . }}-apikey
  labels:
    {{- include "clusterstate-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.suppline.apiKey | quote }}
{{- end }}
