apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suppline.fullname" . }}-trivy-logs
  labels:
    {{- include "suppline.labels" . | nindent 4 }}
data:
  trivy-json-logs.sh: |
{{ .Files.Get "files/trivy-json-logs.sh" | indent 4 }}
